// This file is auto-generated by @hey-api/openapi-ts

export type Edge = {
    start: number;
    end: number;
    id: number;
};

export type EdgeBase = {
    start: number;
    end: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Node = {
    type: NodeType;
    label: string;
    code: string;
    id: number;
};

export type NodeBase = {
    type: NodeType;
    label: string;
    code: string;
};

export type NodeNew = {
    type: NodeType;
};

export type NodeType = 'input' | 'output' | 'user_program' | 'program' | 'comparator';

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetAllEdgesApiEdgesGetResponse = Array<Edge>;

export type CreateEdgeApiEdgesPostData = {
    requestBody: EdgeBase;
};

export type CreateEdgeApiEdgesPostResponse = unknown;

export type DeleteEdgeApiEdgesIdDeleteData = {
    id: number;
};

export type DeleteEdgeApiEdgesIdDeleteResponse = unknown;

export type GetAllNodesApiNodesGetResponse = Array<Node>;

export type CreateNodeApiNodesPostData = {
    requestBody: NodeNew;
};

export type CreateNodeApiNodesPostResponse = unknown;

export type GetNodeApiNodesIdGetData = {
    id: number;
};

export type GetNodeApiNodesIdGetResponse = Node;

export type UpdateNodeApiNodesIdPutData = {
    id: number;
    requestBody: NodeBase;
};

export type UpdateNodeApiNodesIdPutResponse = unknown;

export type DeleteNodeApiNodesIdDeleteData = {
    id: number;
};

export type DeleteNodeApiNodesIdDeleteResponse = unknown;

export type GetAllEdgesApiProgramsRunPostResponse = unknown;